dist: xenial
sudo: yes
language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py install

script:
  - python -c "import pyinfraformat as pif; pif.Holes()"
