dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py install
  - pip install coveralls

script:
  - pytest -v pyinfraformat/tests/ --cov=pyinfraformat/
  - python -m pydocstyle --convention=numpy pyinfraformat/
  - python -m black -l 100 --check pyinfraformat/
  - python -m pylint pyinfraformat/

after_success:
  - echo "Success!"
  - coveralls
